package com.dyz.persist.roledata.user;

public class User {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_user.f_id
     *
     * @ibatorgenerated Fri Jan 30 10:52:50 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_user.f_name
     *
     * @ibatorgenerated Fri Jan 30 10:52:50 CST 2015
     */
    private String name;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_user.f_phonenumber
     *
     * @ibatorgenerated Fri Jan 30 10:52:50 CST 2015
     */
    private String phonenumber;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_user.f_email
     *
     * @ibatorgenerated Fri Jan 30 10:52:50 CST 2015
     */
    private String email;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_user.f_passwd
     *
     * @ibatorgenerated Fri Jan 30 10:52:50 CST 2015
     */
    private String passwd;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_user.f_regdate
     *
     * @ibatorgenerated Fri Jan 30 10:52:50 CST 2015
     */
    private Long regdate;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_user.f_id
     *
     * @return the value of t_user.f_id
     *
     * @ibatorgenerated Fri Jan 30 10:52:50 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_user.f_id
     *
     * @param id the value for t_user.f_id
     *
     * @ibatorgenerated Fri Jan 30 10:52:50 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_user.f_name
     *
     * @return the value of t_user.f_name
     *
     * @ibatorgenerated Fri Jan 30 10:52:50 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_user.f_name
     *
     * @param name the value for t_user.f_name
     *
     * @ibatorgenerated Fri Jan 30 10:52:50 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_user.f_phonenumber
     *
     * @return the value of t_user.f_phonenumber
     *
     * @ibatorgenerated Fri Jan 30 10:52:50 CST 2015
     */
    public String getPhonenumber() {
        return phonenumber;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_user.f_phonenumber
     *
     * @param phonenumber the value for t_user.f_phonenumber
     *
     * @ibatorgenerated Fri Jan 30 10:52:50 CST 2015
     */
    public void setPhonenumber(String phonenumber) {
        this.phonenumber = phonenumber;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_user.f_email
     *
     * @return the value of t_user.f_email
     *
     * @ibatorgenerated Fri Jan 30 10:52:50 CST 2015
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_user.f_email
     *
     * @param email the value for t_user.f_email
     *
     * @ibatorgenerated Fri Jan 30 10:52:50 CST 2015
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_user.f_passwd
     *
     * @return the value of t_user.f_passwd
     *
     * @ibatorgenerated Fri Jan 30 10:52:50 CST 2015
     */
    public String getPasswd() {
        return passwd;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_user.f_passwd
     *
     * @param passwd the value for t_user.f_passwd
     *
     * @ibatorgenerated Fri Jan 30 10:52:50 CST 2015
     */
    public void setPasswd(String passwd) {
        this.passwd = passwd;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_user.f_regdate
     *
     * @return the value of t_user.f_regdate
     *
     * @ibatorgenerated Fri Jan 30 10:52:50 CST 2015
     */
    public Long getRegdate() {
        return regdate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_user.f_regdate
     *
     * @param regdate the value for t_user.f_regdate
     *
     * @ibatorgenerated Fri Jan 30 10:52:50 CST 2015
     */
    public void setRegdate(Long regdate) {
        this.regdate = regdate;
    }
}